### ISSUE TITLE
confirm documentation for `format` in timeserie

### ISSUE THREAD

**Issue by mgravey** [Rafnuss/GeoPressureServer#4]

**Comment by mgravey** [comment]
It's not really possible to provide another format than CSV. GEE propose other formats, but for example son is a list of structures and not a structure of list ? Should we still provide both ?

**Comment by Rafnuss** [comment]
Ok, let's make thing simple. I suggest we remove it.

**Comment by Rafnuss** [comment]
Actually, I let you close this once you've remove it in the response.
